# Generated by Django 3.2.5 on 2021-08-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('numero_de_paginas', models.IntegerField()),
                ('editora', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=40)),
                ('lancamento', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonagemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.livromodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalheModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhe', models.CharField(max_length=200)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to='livros.personagemmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CapaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete', models.TextField()),
                ('verso', models.TextField()),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='livros.livromodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
