# Generated by Django 3.2.5 on 2021-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_auto_20210801_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='lancamento',
            field=models.DateField(),
        ),
    ]
