# Generated by Django 3.2.5 on 2021-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livromodel_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='isbn',
            field=models.CharField(max_length=100),
        ),
    ]
