# Generated by Django 3.2.5 on 2021-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_auto_20210801_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagemmodel',
            name='livro',
        ),
        migrations.AddField(
            model_name='personagemmodel',
            name='livro',
            field=models.ManyToManyField(related_name='livros', to='livros.LivroModel'),
        ),
    ]
