# Generated by Django 3.2.5 on 2021-08-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_auto_20210801_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capamodel',
            name='livro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.livromodel'),
        ),
    ]
