# Generated by Django 3.2.5 on 2021-08-01 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_auto_20210801_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capamodel',
            name='livro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livros.livromodel'),
        ),
        migrations.AlterField(
            model_name='comprarlivromodel',
            name='livro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livros.livromodel'),
        ),
    ]
