# Generated by Django 3.2.5 on 2021-08-01 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_auto_20210801_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete', models.TextField()),
                ('verso', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comprar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhe', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='comprarlivromodel',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='detalhemodel',
            name='personagem',
        ),
        migrations.RemoveField(
            model_name='personagemmodel',
            name='livros',
        ),
        migrations.RenameModel(
            old_name='LivroModel',
            new_name='Livro',
        ),
        migrations.DeleteModel(
            name='CapaModel',
        ),
        migrations.DeleteModel(
            name='ComprarLivroModel',
        ),
        migrations.DeleteModel(
            name='DetalheModel',
        ),
        migrations.DeleteModel(
            name='PersonagemModel',
        ),
        migrations.AddField(
            model_name='personagem',
            name='livros',
            field=models.ManyToManyField(related_name='personagens', to='livros.Livro'),
        ),
        migrations.AddField(
            model_name='detalhe',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='livros.personagem'),
        ),
        migrations.AddField(
            model_name='comprar',
            name='livro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Comprars', to='livros.livro'),
        ),
        migrations.AddField(
            model_name='capa',
            name='livro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capa', to='livros.livro'),
        ),
    ]
