# Generated by Django 3.2.5 on 2021-08-01 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0012_auto_20210801_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprar',
            name='livro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Comprar', to='livros.livro'),
        ),
    ]
