# Generated by Django 3.2.5 on 2021-08-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0013_alter_comprar_livro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capa',
            options={'ordering': ['id'], 'verbose_name': 'Capa', 'verbose_name_plural': 'Capas'},
        ),
        migrations.AlterModelOptions(
            name='comprar',
            options={'verbose_name': 'Comprar', 'verbose_name_plural': 'Comprar'},
        ),
        migrations.AlterModelOptions(
            name='detalhe',
            options={'ordering': ['id'], 'verbose_name': 'Detalhe', 'verbose_name_plural': 'Detalhes'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['id'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterModelOptions(
            name='personagem',
            options={'ordering': ['id'], 'verbose_name': 'Personagem', 'verbose_name_plural': 'Personagens'},
        ),
    ]
